using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace ProjectEuler
{
    /// <summary>
    ///Problem 0002 - Even Fibonacci Numbers
    ///Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
    ///1, 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
    ///By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
    ///Answer: 4613732
    /// </summary>
    class Q0002
    {
        public static Tuple<int, string> Problem()
        {
            int next = 0;

            List<int> FibFinal = new List<int>();
            List<int> Fib = new List<int>();
            Fib.Add(1);
            Fib.Add(1);

            int n = 1;

            while (true)
            {
                next = Fib[n] + Fib[n - 1];

                if (next >= 4000000)
                {
                    break;
                }

                Fib.Add(next);
                n++;
            }

            foreach (int elm in Fib)
            {
                if (elm % 2 == 0)
                {
                    FibFinal.Add(elm);
                }
            }
            return Tuple.Create(FibFinal.Sum(), "2");
        }
    }
}
