#Problem 0002 - Even Fibonacci Numbers
#===============================================================================
#Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

#1, 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

#By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

#Answer: 4613732
#===============================================================================

def problem():
    fib = [1, 1]
    n = 1

    while True:
        next = fib[n] + fib[n - 1]
        if next >= 4000000:
            break
        fib.append(next)
        n += 1

    for i in fib:
        if i & 1:
            fib.remove(i)

    return sum(fib)
